Dynamo.start(Mix.env)

defmodule DynamoUploadfileDemo do
  use Dynamo

  endpoint ApplicationRouter

  config :dynamo,
    # The OTP application from where static assets will be served
    # Defaults to the name of the .app file generated by mix
    otp_app: :dynamo_uploadfile_demo,
    # The route from where static assets are served
    # You can turn off static assets by setting it to false
    static_route: "/static"

  # Default functionality available in templates
  templates do
    use Dynamo.Helpers
  end

  initializer :start_otp_app do
    :application.start config[:dynamo][:otp_app]
  end
end
